<?php

namespace BarrelDirectory\Classes\Acf;

if ( ! defined( 'WPINC' ) ) {
  die;
}

class Acf_Setup {
  public function __construct () {
    
  }

  public function init_register () {
    // $this->add_field_groups();
    // add_action('acf/pre_save_post', array($this, 'set_post_status'), 20);
    add_action( 'acf/input/admin_enqueue_scripts', array($this, 'deregister_styles'), 100 );
  }

  public function deregister_styles() {
    if(!is_admin()){
      // wp_deregister_style( 'acf' );
      // wp_deregister_style( 'acf-field-group' );
      // wp_deregister_style( 'acf-global' );
      // wp_deregister_style( 'acf-input' );
      // wp_deregister_style( 'acf-datepicker' );
      // wp_deregister_style( 'acf_pro_input' );
    }
  }

  public function set_post_status( $post_id ) {
    wp_update_post([
      'post_id' => $post_id,
      'post_status' => 'publish'
    ]);
    remove_action('acf/save_post', 'set_post_status', 20);
  }
  
  public function add_field_groups(){

    if( function_exists('acf_add_local_field_group') ):

      acf_add_local_field_group(array(
        'key' => 'group_5cfaf4bc231df',
        'title' => 'Directory - Instructors',
        'fields' => array(
          array(
            'key' => 'field_5cfaf72026b12',
            'label' => 'Basic Info',
            'name' => 'basic_info',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5d0540a99290c',
                'label' => 'Profile Image',
                'name' => 'profile_image',
                'type' => 'image',
                'instructions' => 'Choose images that are either square or landscape-style.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
              array(
                'key' => 'field_5cfaf4eb0c633',
                'label' => 'About',
                'name' => 'about',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
              ),
              array(
                'key' => 'field_5d06e6e246cc3',
                'label' => 'Certifications',
                'name' => 'certifications',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'taxonomy' => 'certification',
                'field_type' => 'checkbox',
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
              ),
              array(
                'key' => 'field_5d1ccfce1b417',
                'label' => 'Languages',
                'name' => 'languages',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'taxonomy' => 'language',
                'field_type' => 'checkbox',
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
              ),
            ),
          ),
          array(
            'key' => 'field_5d13abed82433',
            'label' => 'Location',
            'name' => 'location_json',
            'type' => 'mapbox_geojson',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'mapbox_access_token' => 'pk.eyJ1Ijoicm9iZXJ0cmFlIiwiYSI6ImNqdndhOHFmejRhczYzeW9qYjJrMGQzY3QifQ.OZag22deq5xysi6cQuAEMw',
            'mapbox_map_style' => 'mapbox://styles/robertrae/cjvwoe8bp5bd91cqi6x6bkdjc',
            'height' => 400,
          ),
          array(
            'key' => 'field_5cfaf830b9af4',
            'label' => 'Your Studios',
            'name' => 'your_studios',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5d0d1f6246868',
                'label' => 'Studio',
                'name' => 'studio',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5cfaf848b9af5',
                    'label' => 'Studio Type',
                    'name' => 'studio_type',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'lyt_studio' => 'LYT Studio',
                      'standard' => 'Standard Studio',
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'default_value' => '',
                    'layout' => 'vertical',
                    'return_format' => 'value',
                    'save_other_choice' => 0,
                  ),
                  array(
                    'key' => 'field_5cfb00d6b9af6',
                    'label' => 'LYT Studio',
                    'name' => 'lyt_studio',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                      array(
                        array(
                          'field' => 'field_5cfaf848b9af5',
                          'operator' => '==',
                          'value' => 'lyt_studio',
                        ),
                      ),
                    ),
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'post_type' => array(
                      0 => 'studio',
                    ),
                    'taxonomy' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                  ),
                  array(
                    'key' => 'field_5cfb02060c48a',
                    'label' => 'Studio Address',
                    'name' => 'studio_address',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                      array(
                        array(
                          'field' => 'field_5cfaf848b9af5',
                          'operator' => '==',
                          'value' => 'standard',
                        ),
                      ),
                    ),
                    'wrapper' => array(
                      'width' => '',
                      'class' => 'studio-address__input',
                      'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                      array(
                        'key' => 'field_5cfb018300959',
                        'label' => 'Studio Name',
                        'name' => 'studio_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '100',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                      ),
                      array(
                        'key' => 'field_5cfb02190c48b',
                        'label' => 'Street',
                        'name' => 'studio_street',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '100',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                      ),
                      array(
                        'key' => 'field_5cfb02230c48c',
                        'label' => 'City',
                        'name' => 'studio_city',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '100',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                      ),
                      array(
                        'key' => 'field_5cfb02360c48d',
                        'label' => 'State',
                        'name' => 'studio_state',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                        ),
                        'choices' => array(
                          'Select Your State' => 'Select Your State',
                          'AL' => 'Alabama',
                          'AK' => 'Alaska',
                          'AZ' => 'Arizona',
                          'AR' => 'Arkansas',
                          'CA' => 'California',
                          'CO' => 'Colorado',
                          'CT' => 'Connecticut',
                          'DE' => 'Delaware',
                          'DC' => 'District Of Columbia',
                          'FL' => 'Florida',
                          'GA' => 'Georgia',
                          'HI' => 'Hawaii',
                          'ID' => 'Idaho',
                          'IL' => 'Illinois',
                          'IN' => 'Indiana',
                          'IA' => 'Iowa',
                          'KS' => 'Kansas',
                          'KY' => 'Kentucky',
                          'LA' => 'Louisiana',
                          'ME' => 'Maine',
                          'MD' => 'Maryland',
                          'MA' => 'Massachusetts',
                          'MI' => 'Michigan',
                          'MN' => 'Minnesota',
                          'MS' => 'Mississippi',
                          'MO' => 'Missouri',
                          'MT' => 'Montana',
                          'NE' => 'Nebraska',
                          'NV' => 'Nevada',
                          'NH' => 'New Hampshire',
                          'NJ' => 'New Jersey',
                          'NM' => 'New Mexico',
                          'NY' => 'New York',
                          'NC' => 'North Carolina',
                          'ND' => 'North Dakota',
                          'OH' => 'Ohio',
                          'OK' => 'Oklahoma',
                          'OR' => 'Oregon',
                          'PA' => 'Pennsylvania',
                          'RI' => 'Rhode Island',
                          'SC' => 'South Carolina',
                          'SD' => 'South Dakota',
                          'TN' => 'Tennessee',
                          'TX' => 'Texas',
                          'UT' => 'Utah',
                          'VT' => 'Vermont',
                          'VA' => 'Virginia',
                          'WA' => 'Washington',
                          'WV' => 'West Virginia',
                          'WI' => 'Wisconsin',
                          'WY' => 'Wyoming',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                      ),
                      array(
                        'key' => 'field_5cfb02620c48e',
                        'label' => 'Postal Code',
                        'name' => 'studio_postal_code',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                      ),
                    ),
                  ),
                  array(
                    'key' => 'field_5cfb0fabbf643',
                    'label' => 'Studio Website',
                    'name' => 'studio_website',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                      array(
                        array(
                          'field' => 'field_5cfaf848b9af5',
                          'operator' => '==',
                          'value' => 'standard',
                        ),
                      ),
                    ),
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5d375921f9736',
                    'label' => 'Primary Studio',
                    'name' => 'primary_studio',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                ),
              ),
            ),
          ),
          array(
            'key' => 'field_5cfaf64dbf0c2',
            'label' => 'Contact Info',
            'name' => 'contact_info',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5cfaf65ebf0c3',
                'label' => 'Email',
                'name' => 'email',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '33.33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_5cfaf66dbf0c4',
                'label' => 'Phone',
                'name' => 'phone',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '33.33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_5cfaf6a8bf0c5',
                'label' => 'Website',
                'name' => 'website',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '33.33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
            ),
          ),
          array(
            'key' => 'field_5cfc0c56e7929',
            'label' => 'Social Media',
            'name' => 'social_media',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5cfc0c65e792a',
                'label' => 'Facebook Profile',
                'name' => 'facebook_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5cfc0c81e792b',
                'label' => 'Instagram Profile',
                'name' => 'instagram_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5cfc0c9ae792c',
                'label' => 'Twitter Profile',
                'name' => 'twitter_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5cfc0ca8e792d',
                'label' => 'YouTube Profile',
                'name' => 'youtube_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
            ),
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'instructor',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5cfaf7a2f04c3',
        'title' => 'Directory - Studios',
        'fields' => array(
          array(
            'key' => 'field_5cfaf7a2f2f1a',
            'label' => 'Basic Info',
            'name' => 'basic_info',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5cfaf7a3000c3',
                'label' => 'About',
                'name' => 'about',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
              ),
              array(
                'key' => 'field_5d1ccdafbc5ce',
                'label' => 'Languages',
                'name' => 'languages',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'taxonomy' => 'language',
                'field_type' => 'checkbox',
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
              ),
              array(
                'key' => 'field_5d2e46ecee20a',
                'label' => 'LYT Instructors',
                'name' => 'lyt_instructors',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => 'lyt_instructors',
                ),
                'post_type' => array(
                  0 => 'instructor',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 1,
                'return_format' => 'id',
                'ui' => 1,
              ),
            ),
          ),
          array(
            'key' => 'field_5d1a295e59498',
            'label' => 'Location',
            'name' => 'location_json',
            'type' => 'mapbox_geojson',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'mapbox_access_token' => 'pk.eyJ1Ijoicm9iZXJ0cmFlIiwiYSI6ImNqdndhOHFmejRhczYzeW9qYjJrMGQzY3QifQ.OZag22deq5xysi6cQuAEMw',
            'mapbox_map_style' => 'mapbox://styles/robertrae/cjvwoe8bp5bd91cqi6x6bkdjc',
            'height' => 400,
            'zzzheight' => 676666,
            'marker' => 1261,
            'required_address_fields' => array(
              0 => 'city',
            ),
          ),
          array(
            'key' => 'field_5cfaf7a2f3061',
            'label' => 'Contact Info',
            'name' => 'contact_info',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5cfaf7a30b85b',
                'label' => 'Email',
                'name' => 'email',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_5cfaf7a30b90f',
                'label' => 'Phone',
                'name' => 'phone',
                'type' => 'text',
                'instructions' => 'Only use numbers. It will be formatted for display.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'ex: 2499432114',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_5cfaf7a30b9f9',
                'label' => 'Website',
                'name' => 'website',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
            ),
          ),
          array(
            'key' => 'field_5cfc0ce506a35',
            'label' => 'Social media',
            'name' => 'social_media',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5cfc0cf406a36',
                'label' => 'Facebook Profile',
                'name' => 'facebook_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5cfc0d0806a37',
                'label' => 'Instagram Profile',
                'name' => 'instagram_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5cfc0d0d06a39',
                'label' => 'Twitter Profile',
                'name' => 'twitter_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5cfc0d0b06a38',
                'label' => 'YouTube Profile',
                'name' => 'youtube_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
            ),
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'studio',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5d0bbd2095a1f',
        'title' => 'Directory - User',
        'fields' => array(
          array(
            'key' => 'field_5d0be8faaad1b',
            'label' => 'Profile Post',
            'name' => 'profile_post',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'instructor',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'user_role',
              'operator' => '==',
              'value' => 'instructor',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
      ));
      
      endif;
  }
}
